# numpy methodlar

In [1]:
import numpy as np


In [2]:
benimDizim = np.arange(0,15)

In [3]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
benimDizim[5]

5

In [5]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

In [6]:
benimDizim[3:5] = -8

In [7]:
benimDizim

array([ 0,  1,  2, -8, -8,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
# Bir dizide slicing yapıldığında ve bu slice içinde değişiklik yapıldığında diziyi direkt etkiler
# Bunun için dizinin bir kopyası alınır ve orada işlemler yapılır.
baskaDizi = np.arange(24)

In [16]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [17]:
slicingDizi = baskaDizi[3:9]

In [18]:
slicingDizi

array([3, 4, 5, 6, 7, 8])

In [19]:
slicingDizi[:] = 700

In [20]:
baskaDizi

array([  0,   1,   2, 700, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [21]:
benimDizim = np.arange(24)


In [22]:
benimDizimKopya = benimDizim.copy()

In [23]:
slicingDizi = benimDizimKopya[3:9]

In [24]:
slicingDizi

array([3, 4, 5, 6, 7, 8])

In [25]:
slicingDizi[:] = 700

In [26]:
benimDizim 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [27]:
benimDizimKopya

array([  0,   1,   2, 700, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

## numpy matriksler

In [28]:
benimListem = [[10,20,30],[20,30,40],[40,50,60]]

In [29]:
benimListem

[[10, 20, 30], [20, 30, 40], [40, 50, 60]]

In [30]:
benimNumpyListem = np.array(benimListem)

In [31]:
benimNumpyListem

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

### indexler

In [32]:
benimNumpyListem[0]

array([10, 20, 30])

In [33]:
benimNumpyListem[1,2]

40

In [34]:
benimNumpyListem[1:,1:]

array([[30, 40],
       [50, 60]])

In [35]:
yeniListe = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [36]:
yeniMatriks = np.array(yeniListe)

In [37]:
yeniMatriks

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
# index içinde [] parantez içindeki istenilen satırları çeker 

yeniMatriks[[4,2,0]]

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

### operasyonlar

In [41]:
yeniBirDizi = np.random.randint(1,100,20)

In [42]:
yeniBirDizi

array([ 3, 39, 30, 51, 60, 97, 80, 86, 59, 18,  7,  3,  9, 44, 79, 39, 37,
        8, 52, 64])

In [43]:
yeniBirDizi > 24

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True, False,
        True,  True])

In [44]:
yeniBirDizi[yeniBirDizi > 24]

array([39, 30, 51, 60, 97, 80, 86, 59, 44, 79, 39, 37, 52, 64])

In [45]:
sonDizi = np.arange(24)

In [46]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [47]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [48]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [49]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [50]:
sonDizi / sonDizi

C:\Users\Lenova\AppData\Local\Temp\ipykernel_14696\1312094733.py:1: RuntimeWarning: invalid value encountered in divide
  sonDizi / sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [51]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])